travis:
  secure:
    BINSTAR_TOKEN: Qj4w+FQm4faaYes9m5xtwBNF8bKWgbN8qVpAPF401RNV2sauXJSaLMKbvZOIVnTSoYiBqOSNDfMFtSnlpBy4WmtRFDPzdn8ejpi9ute426Man2K+M3O0MVn3brxUgMuxhcr68dXhW8CWW/GeHoZewAVHrU9wzqdNBVqu1QQbkXhfKbW2FIzfiIm2BQd9us4c4L7g4tEJp0Gtr5xrkPmYYni/lFv5rz5MknAM6DdsYwCnpYcdglCB1xfaOfECiuLAo+UnxbvbJk80UE7ePTEUe0CAj+XYPHpmZiDcGna0hpEsIU6ju/9WOZEk71zcHqikioLRedIz21u4Fly0c7/nXlwNmYYm9Wo4w7CauZRmnZfsCZShnpVzT8tgblbulz9JkVCf+9zZIoj1VIDPdRwN/k6+eVpvHRHpP8UvuZZqY4ALZMFPd9ztxMTxzzlGLrnAPHFlI0rwgu+Aqow3wpE+tC2hQLobnlUzIifsMNLFJP1oX1D8MXD+oUlKkOMM8jkAf47nMUG6C3YwNgvluFYWSimbjI4xo3Ez9/d22OzEJ3kGXicwza/2Lro8JvSNarRXXZwkS+t7S8B4o6wE6KHR3J0dEv3SX8XYVzLz7EEIQ5z59zlepvW082tmlhtY9NvTmBPcbMpBRKcqkaNFQeR90/0Wa6oTzoBvOYWkZaXGTxU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
