travis:
  secure:
    BINSTAR_TOKEN: WiVHsdqb30fmVPanIR+0Un6p6UgCdsXsnWHOUVTUgTggfXgcqlAc6ol31Q8TUG3KGoym/OgamIBdg3p6pWNVm1clId5IuSbQIb/irYUQGn5qIzXQ5AMd9z9plY8dhr6g67nfZEF5Ib2nV7RxL+Gxq67a61YQiJLgteH6TOrBuaEJvpnf76mpLWGrmT9utqGX9RVJRD0ZHlZUrCktZmgnC/fi7qOLURgJxtt57tS+TR8zVl38zT9WQ8WoJEo5NO3ceK1qgZCORPntU+bKvIl75kqweAOIE3cujtLx1xhXGSk/i4yluDc50IsJrn+1lV1v0iFnAaFODNALPJFJPHD80wMTg7HgMnC+yZ/5qWS1NiHZInO1XVnk9KlJE59ATJPnS3qHHtwGBEB3AUR04gq1OggIA69W7KUtLhrYcjFJ4P5GC7n+hy48b+V2Xw3g2R1PrhocRULUDEwIky/cq7xB8nDLakmtMXvPKPfqLbkGTDTjDHcbsTLby4QYClqYqmCuwnWP53oX7+xeDOtDl0rEazu7FMfiSLfSH9Qp4VGPoVzbfgnm+yASRBEQ7YwjiTYusyiema5TUz6HgTxwuO5IH1HW5Nhckc8vmkZ3pA1+m8713LP9V76aOAAysrid6fIcisP0zKcYCiNumJG13yZRh4G2FtMgxJpJeNNK3TDq+7I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
