travis:
  secure:
    BINSTAR_TOKEN: oigyWZ9Qn/RdFHsYxzCuiBsz/w/4mxfoHZnKtOPPv0PT1cr5YeX8OiygLzxugyepM2gkUXmZDI93fze3NKxk+wURoAEKQx+otgIWi5qXkbHy7FNTdongzKp79ApV9PluTdhrRrD97P88UepZUpsZ4gQs12dN4+XipKBEYVe91h27EKMv9wsRMz9HyJYYSkNOjwwbgcbUD6fkqrH+1b0GDucNcL5kPCZeEWsPSXgMLDva1bJ5fvtg4H/ePk9SGACR5w4VyKNCE6c/cQkuORPqSPGH8wngoO4t5c+UlOosl1+ms+RFIZi3tHr2+okfHeEt3TtPI51rLdPcg8Mgp1ckGkI9G3vJw5RkrlDrRG5OOYeZMurvAEvX2uutf5U9vaZqTv+zjxo9T0cmuemFqDWEkvwpgRJ7nyOnrpsI/Y05Ey5or87T3rHVRlBeS6VNWB6KH5sVHuklfn+zZPvV+jMcH4iTGpmj75oXdOWBxhRFt4t1fnAEdMRYCAbwfQYgQ8wdL8gz36RXJZSkHytENmrEFe0dqegnfrbUCEZL/A70x7F+j9JWmkCyqFoVIWYEFY3ESgdFh5tysCrMoNWLP/59Bk5RpeuKcH4Jw9s2hKYq89afO7jOg94H9qGrxOyAz/HF6fcjrTQaUindkCnqPuiLGDCllMmVuT+jU7Q0FlEgWB8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
